#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "==== Running PHPCS ==== \n";
phpcs --standard=phpcs.xml .

echo "${GREEN}PHPCS Validation Passed Successfully ${NC} \n";

echo "${YELLOW}Building assets before commiting...${NC}";

cd assets # in assets directory
npm run build:all

cd .. # Now in root directory
git add assets/build languages